from datetime import datetime, timedelta, timezone
from pymongo.database import Database
from app.repositories.inventory_repository import InventoryRepository

NOW = datetime.now(timezone.utc)

# Lazy import to avoid circular import during startup
def _hash(plain: str) -> str:
    from app.core.auth_security import hash_password
    return hash_password(plain)


def run(db: Database) -> None:
    """Seeds the MongoDB with comprehensive realistic supply chain data."""
    inventory_repo = InventoryRepository(db)

    # Upserts below make startup additive: existing records are preserved while
    # missing demo records and newly introduced fields are backfilled.

    # ------------------------------------------------------------------
    # 0. USER ACCOUNTS  (admin, suppliers, users — hashed passwords)
    # ------------------------------------------------------------------
    users = [
        # Demo Admin accounts
        {
            "user_id": "USR-001",
            "name": "Alex Whitfield",
            "email": "admin@scda.io",
            "password_hash": _hash("Admin@1234"),
            "role": "admin",
            "company_name": "Atlas Supply Chain Control Tower",
            "is_active": True,
            "created_at": (NOW - timedelta(days=90)).isoformat(),
            "updated_at": NOW.isoformat(),
            "pending_reset_token": None,
        },
        {
            "user_id": "USR-001-ALT",
            "name": "Alex Whitfield",
            "email": "alex.whitfield@atlas-scm.io",
            "password_hash": _hash("Admin@1234"),
            "role": "admin",
            "company_name": "Atlas Supply Chain Control Tower",
            "is_active": True,
            "created_at": (NOW - timedelta(days=90)).isoformat(),
            "updated_at": NOW.isoformat(),
            "pending_reset_token": None,
        },
        {
            "user_id": "USR-001-TRACE",
            "name": "Team TRACE Admin",
            "email": "admin@trace.com",
            "password_hash": _hash("Admin@1234"),
            "role": "admin",
            "company_name": "Team TRACE Control Tower",
            "is_active": True,
            "created_at": (NOW - timedelta(days=90)).isoformat(),
            "updated_at": NOW.isoformat(),
            "pending_reset_token": None,
        },
        # Demo Supplier accounts
        {
            "user_id": "USR-002-DEMO",
            "name": "Alpha Components Supplier",
            "email": "supplier@alpha-components.in",
            "password_hash": _hash("Supplier@1234"),
            "role": "supplier",
            "company_name": "Alpha Components India Ltd.",
            "supplier_id": "SUP-001",
            "is_active": True,
            "created_at": (NOW - timedelta(days=60)).isoformat(),
            "updated_at": NOW.isoformat(),
            "pending_reset_token": None,
        },
        {
            "user_id": "USR-002",
            "name": "Ravi Kapoor",
            "email": "supplier@meridianelectro.in",
            "password_hash": _hash("Supplier@1234"),
            "role": "supplier",
            "company_name": "Meridian Electro Components Pvt. Ltd.",
            "supplier_id": "SUP-001",
            "is_active": True,
            "created_at": (NOW - timedelta(days=60)).isoformat(),
            "updated_at": NOW.isoformat(),
            "pending_reset_token": None,
        },
        # Supplier user linked to SUP-002
        {
            "user_id": "USR-003",
            "name": "Birgit Hoffmann",
            "email": "supplier@bergmann-precision.de",
            "password_hash": _hash("Supplier@1234"),
            "role": "supplier",
            "company_name": "Bergmann Precision Supplies GmbH",
            "supplier_id": "SUP-002",
            "is_active": True,
            "created_at": (NOW - timedelta(days=55)).isoformat(),
            "updated_at": NOW.isoformat(),
            "pending_reset_token": None,
        },
        # Supplier user linked to SUP-003
        {
            "user_id": "USR-004",
            "name": "Gerald Tan",
            "email": "supplier@swiftcircuit.sg",
            "password_hash": _hash("Supplier@1234"),
            "role": "supplier",
            "company_name": "Swift Circuit Supply Pte Ltd",
            "supplier_id": "SUP-003",
            "is_active": True,
            "created_at": (NOW - timedelta(days=50)).isoformat(),
            "updated_at": NOW.isoformat(),
            "pending_reset_token": None,
        },
        # Demo Regular user accounts
        {
            "user_id": "USR-005-DEMO",
            "name": "Operations User",
            "email": "user@scda.io",
            "password_hash": _hash("User@1234"),
            "role": "user",
            "company_name": None,
            "is_active": True,
            "created_at": (NOW - timedelta(days=30)).isoformat(),
            "updated_at": NOW.isoformat(),
            "pending_reset_token": None,
        },
        {
            "user_id": "USR-005",
            "name": "Priya Sharma",
            "email": "priya.sharma@atlas-scm.io",
            "password_hash": _hash("User@1234"),
            "role": "user",
            "company_name": None,
            "is_active": True,
            "created_at": (NOW - timedelta(days=30)).isoformat(),
            "updated_at": NOW.isoformat(),
            "pending_reset_token": None,
        },
        # Regular user (operations manager)
        {
            "user_id": "USR-006",
            "name": "Rohan Mehra",
            "email": "rohan.mehra@atlas-scm.io",
            "password_hash": _hash("User@1234"),
            "role": "user",
            "company_name": None,
            "is_active": True,
            "created_at": (NOW - timedelta(days=20)).isoformat(),
            "updated_at": NOW.isoformat(),
            "pending_reset_token": None,
        },
        # Supplier user for SUP-005
        {
            "user_id": "USR-007",
            "name": "Erik van Dijk",
            "email": "vip@vandijksupply.eu",
            "password_hash": _hash("Supplier@1234"),
            "role": "supplier",
            "company_name": "Van Dijk Fast-Track Supply B.V.",
            "supplier_id": "SUP-005",
            "is_active": True,
            "created_at": (NOW - timedelta(days=45)).isoformat(),
            "updated_at": NOW.isoformat(),
            "pending_reset_token": None,
        },
        # Second admin
        {
            "user_id": "USR-008",
            "name": "Duncan Lee",
            "email": "duncan.lee@atlas-scm.io",
            "password_hash": _hash("Admin@1234"),
            "role": "admin",
            "company_name": "Atlas Supply Chain Control Tower",
            "is_active": True,
            "created_at": (NOW - timedelta(days=80)).isoformat(),
            "updated_at": NOW.isoformat(),
            "pending_reset_token": None,
        },
    ]
    for u in users:
        db["users"].update_one({"email": u["email"]}, {"$set": u}, upsert=True)
    print(f"   Users:             {len(users)} accounts seeded")

    # ------------------------------------------------------------------
    # 1. INVENTORY  (18 items — normal, low, critical, over-stock, broken)
    # ------------------------------------------------------------------
    inventory_data = [
        # Normal stock — well above safety stock
        {
            "component_id": "CMP-001",
            "name": "Precision Resistor 100Ω",
            "current_stock": 2400,
            "usable_stock": 2400,
            "daily_usage": 120.0,
            "safety_stock": 360,
            "days_of_supply": 20,
            "location": "Warehouse-A",
            "last_updated": NOW.isoformat(),
        },
        # Low stock — approaching safety stock
        {
            "component_id": "CMP-002",
            "name": "Capacitor 10µF",
            "current_stock": 480,
            "usable_stock": 420,
            "daily_usage": 200.0,
            "safety_stock": 400,
            "days_of_supply": 2,
            "location": "Warehouse-A",
            "last_updated": NOW.isoformat(),
        },
        # Critical stock — below safety stock, production at risk
        {
            "component_id": "CMP-003",
            "name": "Microcontroller MCU-32X",
            "current_stock": 80,
            "usable_stock": 60,
            "daily_usage": 50.0,
            "safety_stock": 150,
            "days_of_supply": 1,
            "location": "Warehouse-B",
            "last_updated": NOW.isoformat(),
        },
        # Hero scenario component — being disrupted
        {
            "component_id": "CMP-004",
            "name": "Voltage Regulator VR-5A",
            "current_stock": 390,
            "usable_stock": 390,
            "daily_usage": 90.0,
            "safety_stock": 100,
            "days_of_supply": 4,
            "location": "Warehouse-A",
            "last_updated": NOW.isoformat(),
        },
        # Healthy stock
        {
            "component_id": "CMP-005",
            "name": "Inductor 47µH",
            "current_stock": 3000,
            "usable_stock": 3000,
            "daily_usage": 50.0,
            "safety_stock": 150,
            "days_of_supply": 60,
            "location": "Warehouse-C",
            "last_updated": NOW.isoformat(),
        },
        # Second hero scenario component — also disrupted
        {
            "component_id": "CMP-006",
            "name": "MOSFET Transistor N-Channel",
            "current_stock": 100,
            "usable_stock": 80,
            "daily_usage": 20.0,
            "safety_stock": 50,
            "days_of_supply": 4,
            "location": "Warehouse-B",
            "last_updated": NOW.isoformat(),
        },
        # Over-stock — excess that can be re-allocated
        {
            "component_id": "CMP-007",
            "name": "PCB Substrate FR4",
            "current_stock": 5000,
            "usable_stock": 5000,
            "daily_usage": 30.0,
            "safety_stock": 90,
            "days_of_supply": 166,
            "location": "Warehouse-D",
            "last_updated": NOW.isoformat(),
        },
        # Inconsistent entry — will be detected by LLM as anomaly
        {
            "component_id": "CMP-999",
            "name": "Unknown Component",
            "current_stock": 200,
            "usable_stock": 200,
            "daily_usage": 0.0,   # zero usage but stock exists — anomaly
            "safety_stock": 0,
            "days_of_supply": None,
            "location": "UNKNOWN",
            "last_updated": (NOW - timedelta(days=45)).isoformat(),  # stale
        },
        # Additional components for dashboard richness
        {
            "component_id": "CMP-008",
            "name": "Op-Amp IC LM741",
            "current_stock": 1800,
            "usable_stock": 1750,
            "daily_usage": 80.0,
            "safety_stock": 240,
            "days_of_supply": 21,
            "location": "Warehouse-A",
            "last_updated": NOW.isoformat(),
        },
        {
            "component_id": "CMP-009",
            "name": "Schottky Diode 1N5819",
            "current_stock": 6000,
            "usable_stock": 5800,
            "daily_usage": 150.0,
            "safety_stock": 450,
            "days_of_supply": 38,
            "location": "Warehouse-C",
            "last_updated": NOW.isoformat(),
        },
        {
            "component_id": "CMP-010",
            "name": "Crystal Oscillator 16MHz",
            "current_stock": 320,
            "usable_stock": 280,
            "daily_usage": 40.0,
            "safety_stock": 120,
            "days_of_supply": 7,
            "location": "Warehouse-B",
            "last_updated": NOW.isoformat(),
        },
        {
            "component_id": "CMP-011",
            "name": "NPN Transistor BC547",
            "current_stock": 12000,
            "usable_stock": 12000,
            "daily_usage": 300.0,
            "safety_stock": 900,
            "days_of_supply": 40,
            "location": "Warehouse-D",
            "last_updated": NOW.isoformat(),
        },
        {
            "component_id": "CMP-012",
            "name": "Zener Diode 5.1V",
            "current_stock": 2200,
            "usable_stock": 2100,
            "daily_usage": 60.0,
            "safety_stock": 180,
            "days_of_supply": 35,
            "location": "Warehouse-A",
            "last_updated": NOW.isoformat(),
        },
        {
            "component_id": "CMP-013",
            "name": "SMD Resistor Array 4.7kΩ",
            "current_stock": 85000,
            "usable_stock": 85000,
            "daily_usage": 500.0,
            "safety_stock": 1500,
            "days_of_supply": 170,
            "location": "Warehouse-D",
            "last_updated": NOW.isoformat(),
        },
        {
            "component_id": "CMP-014",
            "name": "DC-DC Converter Module 5V",
            "current_stock": 140,
            "usable_stock": 120,
            "daily_usage": 25.0,
            "safety_stock": 75,
            "days_of_supply": 4,
            "location": "Warehouse-B",
            "last_updated": NOW.isoformat(),
        },
        {
            "component_id": "CMP-015",
            "name": "Hall Effect Sensor SS495A",
            "current_stock": 500,
            "usable_stock": 500,
            "daily_usage": 35.0,
            "safety_stock": 105,
            "days_of_supply": 14,
            "location": "Warehouse-C",
            "last_updated": NOW.isoformat(),
        },
        {
            "component_id": "CMP-016",
            "name": "Thermistor NTC 10kΩ",
            "current_stock": 3800,
            "usable_stock": 3800,
            "daily_usage": 90.0,
            "safety_stock": 270,
            "days_of_supply": 42,
            "location": "Warehouse-A",
            "last_updated": NOW.isoformat(),
        },
        {
            "component_id": "CMP-017",
            "name": "Li-Ion Battery Cell 18650",
            "current_stock": 220,
            "usable_stock": 180,
            "daily_usage": 45.0,
            "safety_stock": 135,
            "days_of_supply": 4,
            "location": "Warehouse-B",
            "last_updated": NOW.isoformat(),
        },
    ]
    for item in inventory_data:
        inventory_repo.update({"component_id": item["component_id"]}, item)

    # ------------------------------------------------------------------
    # 2. SUPPLIERS  (16 — high/medium/low reliability, various certs)
    # ------------------------------------------------------------------
    suppliers = [
        # Primary delayed supplier (hero scenario)
        {
            "supplier_id": "SUP-001",
            "name": "Meridian Electro Components Pvt. Ltd.",
            "contact_email": "orders@meridianelectro.in",
            "quality_score": 88,
            "reliability_score": 72,
            "on_time_delivery_rate": 0.68,
            "certifications": "ISO9001",
            "lead_time_days": 14,
            "min_order_qty": 100,
            "country": "India",
            "status": "ACTIVE",
            "blacklisted": False,
        },
        # Alternative high-quality supplier
        {
            "supplier_id": "SUP-002",
            "name": "Bergmann Precision Supplies GmbH",
            "contact_email": "supply@bergmann-precision.de",
            "quality_score": 95,
            "reliability_score": 91,
            "on_time_delivery_rate": 0.94,
            "certifications": "ISO9001,RoHS",
            "lead_time_days": 7,
            "min_order_qty": 50,
            "country": "Germany",
            "status": "ACTIVE",
            "blacklisted": False,
        },
        # Expedite-capable supplier (higher cost)
        {
            "supplier_id": "SUP-003",
            "name": "Swift Circuit Supply Pte Ltd",
            "contact_email": "urgent@swiftcircuit.sg",
            "quality_score": 80,
            "reliability_score": 85,
            "on_time_delivery_rate": 0.88,
            "certifications": "RoHS",
            "lead_time_days": 3,
            "min_order_qty": 200,
            "country": "Singapore",
            "status": "ACTIVE",
            "blacklisted": False,
        },
        # Budget supplier — lower reliability, no certs
        {
            "supplier_id": "SUP-004",
            "name": "Hongwei Bulk Electronics Co., Ltd.",
            "contact_email": "sales@hongweibulk.cn",
            "quality_score": 70,
            "reliability_score": 62,
            "on_time_delivery_rate": 0.60,
            "certifications": "",
            "lead_time_days": 21,
            "min_order_qty": 500,
            "country": "China",
            "status": "ACTIVE",
            "blacklisted": False,
        },
        # Premium fast supplier
        {
            "supplier_id": "SUP-005",
            "name": "Van Dijk Fast-Track Supply B.V.",
            "contact_email": "vip@vandijksupply.eu",
            "quality_score": 93,
            "reliability_score": 96,
            "on_time_delivery_rate": 0.97,
            "certifications": "ISO9001,RoHS,IATF16949",
            "lead_time_days": 5,
            "min_order_qty": 100,
            "country": "Netherlands",
            "status": "ACTIVE",
            "blacklisted": False,
        },
        # Suspended supplier — flagged for compliance issues
        {
            "supplier_id": "SUP-006",
            "name": "Fuxin Discount Parts Co.",
            "contact_email": "info@fuxindiscount.cn",
            "quality_score": 55,
            "reliability_score": 40,
            "on_time_delivery_rate": 0.35,
            "certifications": "",
            "lead_time_days": 30,
            "min_order_qty": 1000,
            "country": "China",
            "status": "SUSPENDED",
            "blacklisted": True,
        },
        # New supplier — under evaluation
        {
            "supplier_id": "SUP-007",
            "name": "Nova Emerging Components Pvt Ltd",
            "contact_email": "hello@novaemerging.in",
            "quality_score": 78,
            "reliability_score": None,  # no history — anomaly for LLM to flag
            "on_time_delivery_rate": None,
            "certifications": "ISO9001",
            "lead_time_days": 10,
            "min_order_qty": 100,
            "country": "India",
            "status": "UNDER_EVALUATION",
            "blacklisted": False,
        },
        # High-volume, slow delivery supplier
        {
            "supplier_id": "SUP-008",
            "name": "Taihe Mass Production Co., Ltd.",
            "contact_email": "bulk@taihemass.tw",
            "quality_score": 82,
            "reliability_score": 78,
            "on_time_delivery_rate": 0.75,
            "certifications": "ISO9001,RoHS",
            "lead_time_days": 28,
            "min_order_qty": 2000,
            "country": "Taiwan",
            "status": "ACTIVE",
            "blacklisted": False,
        },
        # Additional suppliers for dashboard richness
        {
            "supplier_id": "SUP-009",
            "name": "Kaida Semiconductor Ltd.",
            "contact_email": "sales@kaida-semi.jp",
            "quality_score": 92,
            "reliability_score": 89,
            "on_time_delivery_rate": 0.91,
            "certifications": "ISO9001,RoHS,IATF16949",
            "lead_time_days": 10,
            "min_order_qty": 250,
            "country": "Japan",
            "status": "ACTIVE",
            "blacklisted": False,
        },
        {
            "supplier_id": "SUP-010",
            "name": "Ridgeline Circuit Works Inc.",
            "contact_email": "procurement@ridgelinecircuit.us",
            "quality_score": 85,
            "reliability_score": 80,
            "on_time_delivery_rate": 0.82,
            "certifications": "ISO9001",
            "lead_time_days": 12,
            "min_order_qty": 150,
            "country": "USA",
            "status": "ACTIVE",
            "blacklisted": False,
        },
        {
            "supplier_id": "SUP-011",
            "name": "Falkenstein Elektronik GmbH",
            "contact_email": "orders@falkenstein-elektronik.de",
            "quality_score": 91,
            "reliability_score": 87,
            "on_time_delivery_rate": 0.90,
            "certifications": "ISO9001,RoHS",
            "lead_time_days": 8,
            "min_order_qty": 100,
            "country": "Germany",
            "status": "ACTIVE",
            "blacklisted": False,
        },
        {
            "supplier_id": "SUP-012",
            "name": "Hanbit Components Korea Co., Ltd.",
            "contact_email": "supply@hanbitcomp.kr",
            "quality_score": 87,
            "reliability_score": 84,
            "on_time_delivery_rate": 0.86,
            "certifications": "ISO9001,RoHS",
            "lead_time_days": 9,
            "min_order_qty": 200,
            "country": "South Korea",
            "status": "ACTIVE",
            "blacklisted": False,
        },
        {
            "supplier_id": "SUP-013",
            "name": "Marina Micro Systems Pte Ltd",
            "contact_email": "info@marinamicro.sg",
            "quality_score": 76,
            "reliability_score": 71,
            "on_time_delivery_rate": 0.73,
            "certifications": "RoHS",
            "lead_time_days": 15,
            "min_order_qty": 300,
            "country": "Singapore",
            "status": "ACTIVE",
            "blacklisted": False,
        },
        {
            "supplier_id": "SUP-014",
            "name": "Ashford Technologies Ltd",
            "contact_email": "orders@ashfordtech.co.uk",
            "quality_score": 89,
            "reliability_score": 83,
            "on_time_delivery_rate": 0.85,
            "certifications": "ISO9001,IATF16949",
            "lead_time_days": 11,
            "min_order_qty": 75,
            "country": "UK",
            "status": "ACTIVE",
            "blacklisted": False,
        },
        {
            "supplier_id": "SUP-015",
            "name": "Suryan Power Supplies Pvt Ltd",
            "contact_email": "sales@suryanpower.in",
            "quality_score": 83,
            "reliability_score": 79,
            "on_time_delivery_rate": 0.80,
            "certifications": "ISO9001",
            "lead_time_days": 16,
            "min_order_qty": 50,
            "country": "India",
            "status": "ACTIVE",
            "blacklisted": False,
        },
        {
            "supplier_id": "SUP-016",
            "name": "Chunghua Passive Components Co.",
            "contact_email": "sales@chunghuapassive.tw",
            "quality_score": 79,
            "reliability_score": 76,
            "on_time_delivery_rate": 0.77,
            "certifications": "RoHS",
            "lead_time_days": 18,
            "min_order_qty": 500,
            "country": "Taiwan",
            "status": "ACTIVE",
            "blacklisted": False,
        },
    ]
    for s in suppliers:
        db["suppliers"].update_one({"supplier_id": s["supplier_id"]}, {"$set": s}, upsert=True)

    # ------------------------------------------------------------------
    # 3. PURCHASE ORDERS  (27 — all status variants for workflow testing)
    # ------------------------------------------------------------------
    purchase_orders = [
        # DELAYED — hero scenario trigger
        {
            "po_id": "PO-001",
            "component_id": "CMP-004",
            "supplier_id": "SUP-001",
            "quantity": 600,
            "unit_price": 140.0,
            "total_value": 84000.0,
            "status": "DELAYED",
            "promised_delivery": (NOW - timedelta(days=3)).isoformat(),
            "current_expected_delivery": (NOW + timedelta(days=8)).isoformat(),
            "delay_days": 11,
            "last_erp_sync": NOW.isoformat(),
            "notes": "Supplier cited raw material shortage",
        },
        # OPEN — just placed
        {
            "po_id": "PO-002",
            "component_id": "CMP-006",
            "supplier_id": "SUP-003",
            "quantity": 300,
            "unit_price": 45.0,
            "total_value": 13500.0,
            "status": "OPEN",
            "promised_delivery": (NOW + timedelta(days=5)).isoformat(),
            "current_expected_delivery": (NOW + timedelta(days=5)).isoformat(),
            "delay_days": 0,
            "last_erp_sync": NOW.isoformat(),
            "notes": "",
        },
        # IN_TRANSIT — on track
        {
            "po_id": "PO-003",
            "component_id": "CMP-001",
            "supplier_id": "SUP-002",
            "quantity": 1200,
            "unit_price": 2.5,
            "total_value": 3000.0,
            "status": "IN_TRANSIT",
            "promised_delivery": (NOW + timedelta(days=2)).isoformat(),
            "current_expected_delivery": (NOW + timedelta(days=2)).isoformat(),
            "delay_days": 0,
            "last_erp_sync": NOW.isoformat(),
            "notes": "Tracking: in customs clearance",
        },
        # AT_RISK — may breach
        {
            "po_id": "PO-004",
            "component_id": "CMP-002",
            "supplier_id": "SUP-004",
            "quantity": 2000,
            "unit_price": 0.8,
            "total_value": 1600.0,
            "status": "AT_RISK",
            "promised_delivery": (NOW + timedelta(days=1)).isoformat(),
            "current_expected_delivery": (NOW + timedelta(days=4)).isoformat(),
            "delay_days": 3,
            "last_erp_sync": NOW.isoformat(),
            "notes": "Supplier confirmed partial shipment only",
        },
        # RECEIVED — completed OK
        {
            "po_id": "PO-005",
            "component_id": "CMP-005",
            "supplier_id": "SUP-005",
            "quantity": 500,
            "unit_price": 1.2,
            "total_value": 600.0,
            "status": "RECEIVED",
            "promised_delivery": (NOW - timedelta(days=5)).isoformat(),
            "current_expected_delivery": (NOW - timedelta(days=5)).isoformat(),
            "delay_days": 0,
            "last_erp_sync": NOW.isoformat(),
            "notes": "Delivered on time, quality inspection passed",
        },
        # CANCELLED — supplier suspended
        {
            "po_id": "PO-006",
            "component_id": "CMP-003",
            "supplier_id": "SUP-006",
            "quantity": 1000,
            "unit_price": 12.0,
            "total_value": 12000.0,
            "status": "CANCELLED",
            "promised_delivery": (NOW + timedelta(days=20)).isoformat(),
            "current_expected_delivery": None,
            "delay_days": 0,
            "last_erp_sync": NOW.isoformat(),
            "notes": "Cancelled due to supplier suspension — compliance violation",
        },
        # DELAYED (high severity — over $50k, requires human approval)
        {
            "po_id": "PO-007",
            "component_id": "CMP-003",
            "supplier_id": "SUP-008",
            "quantity": 5000,
            "unit_price": 12.0,
            "total_value": 60000.0,
            "status": "DELAYED",
            "promised_delivery": (NOW - timedelta(days=7)).isoformat(),
            "current_expected_delivery": (NOW + timedelta(days=14)).isoformat(),
            "delay_days": 21,
            "last_erp_sync": NOW.isoformat(),
            "notes": "Critical delay — production line at risk",
        },
        # ORDERED — monitoring needed
        {
            "po_id": "PO-008",
            "component_id": "CMP-006",
            "supplier_id": "SUP-007",
            "quantity": 400,
            "unit_price": 48.0,
            "total_value": 19200.0,
            "status": "ORDERED",
            "promised_delivery": (NOW + timedelta(days=10)).isoformat(),
            "current_expected_delivery": (NOW + timedelta(days=10)).isoformat(),
            "delay_days": 0,
            "last_erp_sync": NOW.isoformat(),
            "notes": "New supplier — under evaluation, monitoring required",
        },
        # DELAYED — medium severity, autonomous resolution expected
        {
            "po_id": "PO-009",
            "component_id": "CMP-001",
            "supplier_id": "SUP-001",
            "quantity": 300,
            "unit_price": 2.5,
            "total_value": 750.0,
            "status": "DELAYED",
            "promised_delivery": (NOW - timedelta(days=2)).isoformat(),
            "current_expected_delivery": (NOW + timedelta(days=3)).isoformat(),
            "delay_days": 5,
            "last_erp_sync": NOW.isoformat(),
            "notes": "Minor delay — supplier confirmed dispatch",
        },
        # IN_TRANSIT — partial shipment
        {
            "po_id": "PO-010",
            "component_id": "CMP-007",
            "supplier_id": "SUP-002",
            "quantity": 1000,
            "unit_price": 3.2,
            "total_value": 3200.0,
            "status": "IN_TRANSIT",
            "promised_delivery": (NOW + timedelta(days=3)).isoformat(),
            "current_expected_delivery": (NOW + timedelta(days=3)).isoformat(),
            "delay_days": 0,
            "last_erp_sync": NOW.isoformat(),
            "notes": "Partial: 600/1000 units dispatched",
        },
        # OPEN — large order pending confirmation
        {
            "po_id": "PO-011",
            "component_id": "CMP-005",
            "supplier_id": "SUP-005",
            "quantity": 2000,
            "unit_price": 1.2,
            "total_value": 2400.0,
            "status": "OPEN",
            "promised_delivery": (NOW + timedelta(days=7)).isoformat(),
            "current_expected_delivery": (NOW + timedelta(days=7)).isoformat(),
            "delay_days": 0,
            "last_erp_sync": NOW.isoformat(),
            "notes": "",
        },
        # Anomalous PO
        {
            "po_id": "PO-000",
            "component_id": "CMP-999",
            "supplier_id": "SUP-UNKNOWN",
            "quantity": 100,
            "unit_price": 0.0,
            "total_value": 0.0,
            "status": "OPEN",
            "promised_delivery": None,
            "current_expected_delivery": None,
            "delay_days": 0,
            "last_erp_sync": None,
            "notes": "AUTO-GENERATED: supplier reference not found in system",
        },
        # --- Additional POs for dashboard richness ---
        {
            "po_id": "PO-012",
            "component_id": "CMP-008",
            "supplier_id": "SUP-009",
            "quantity": 2000,
            "unit_price": 0.95,
            "total_value": 1900.0,
            "status": "OPEN",
            "promised_delivery": (NOW + timedelta(days=12)).isoformat(),
            "current_expected_delivery": (NOW + timedelta(days=12)).isoformat(),
            "delay_days": 0,
            "last_erp_sync": NOW.isoformat(),
            "notes": "",
        },
        {
            "po_id": "PO-013",
            "component_id": "CMP-009",
            "supplier_id": "SUP-010",
            "quantity": 5000,
            "unit_price": 0.35,
            "total_value": 1750.0,
            "status": "IN_TRANSIT",
            "promised_delivery": (NOW + timedelta(days=4)).isoformat(),
            "current_expected_delivery": (NOW + timedelta(days=4)).isoformat(),
            "delay_days": 0,
            "last_erp_sync": NOW.isoformat(),
            "notes": "Shipment confirmed",
        },
        {
            "po_id": "PO-014",
            "component_id": "CMP-010",
            "supplier_id": "SUP-011",
            "quantity": 800,
            "unit_price": 2.2,
            "total_value": 1760.0,
            "status": "AT_RISK",
            "promised_delivery": (NOW + timedelta(days=2)).isoformat(),
            "current_expected_delivery": (NOW + timedelta(days=6)).isoformat(),
            "delay_days": 4,
            "last_erp_sync": NOW.isoformat(),
            "notes": "Port congestion may cause delay",
        },
        {
            "po_id": "PO-015",
            "component_id": "CMP-011",
            "supplier_id": "SUP-012",
            "quantity": 10000,
            "unit_price": 0.18,
            "total_value": 1800.0,
            "status": "RECEIVED",
            "promised_delivery": (NOW - timedelta(days=3)).isoformat(),
            "current_expected_delivery": (NOW - timedelta(days=3)).isoformat(),
            "delay_days": 0,
            "last_erp_sync": NOW.isoformat(),
            "notes": "Received on time. QC passed.",
        },
        {
            "po_id": "PO-016",
            "component_id": "CMP-012",
            "supplier_id": "SUP-013",
            "quantity": 3000,
            "unit_price": 0.42,
            "total_value": 1260.0,
            "status": "DELAYED",
            "promised_delivery": (NOW - timedelta(days=1)).isoformat(),
            "current_expected_delivery": (NOW + timedelta(days=5)).isoformat(),
            "delay_days": 6,
            "last_erp_sync": NOW.isoformat(),
            "notes": "Customs clearance delay",
        },
        {
            "po_id": "PO-017",
            "component_id": "CMP-013",
            "supplier_id": "SUP-016",
            "quantity": 50000,
            "unit_price": 0.025,
            "total_value": 1250.0,
            "status": "IN_TRANSIT",
            "promised_delivery": (NOW + timedelta(days=6)).isoformat(),
            "current_expected_delivery": (NOW + timedelta(days=6)).isoformat(),
            "delay_days": 0,
            "last_erp_sync": NOW.isoformat(),
            "notes": "",
        },
        {
            "po_id": "PO-018",
            "component_id": "CMP-014",
            "supplier_id": "SUP-014",
            "quantity": 300,
            "unit_price": 18.5,
            "total_value": 5550.0,
            "status": "OPEN",
            "promised_delivery": (NOW + timedelta(days=9)).isoformat(),
            "current_expected_delivery": (NOW + timedelta(days=9)).isoformat(),
            "delay_days": 0,
            "last_erp_sync": NOW.isoformat(),
            "notes": "",
        },
        {
            "po_id": "PO-019",
            "component_id": "CMP-015",
            "supplier_id": "SUP-015",
            "quantity": 600,
            "unit_price": 4.8,
            "total_value": 2880.0,
            "status": "ORDERED",
            "promised_delivery": (NOW + timedelta(days=15)).isoformat(),
            "current_expected_delivery": (NOW + timedelta(days=15)).isoformat(),
            "delay_days": 0,
            "last_erp_sync": NOW.isoformat(),
            "notes": "",
        },
        {
            "po_id": "PO-020",
            "component_id": "CMP-017",
            "supplier_id": "SUP-009",
            "quantity": 500,
            "unit_price": 8.9,
            "total_value": 4450.0,
            "status": "DELAYED",
            "promised_delivery": (NOW - timedelta(days=4)).isoformat(),
            "current_expected_delivery": (NOW + timedelta(days=7)).isoformat(),
            "delay_days": 11,
            "last_erp_sync": NOW.isoformat(),
            "notes": "Battery supply constrained globally",
        },
        {
            "po_id": "PO-021",
            "component_id": "CMP-016",
            "supplier_id": "SUP-008",
            "quantity": 2000,
            "unit_price": 1.15,
            "total_value": 2300.0,
            "status": "RECEIVED",
            "promised_delivery": (NOW - timedelta(days=7)).isoformat(),
            "current_expected_delivery": (NOW - timedelta(days=7)).isoformat(),
            "delay_days": 0,
            "last_erp_sync": NOW.isoformat(),
            "notes": "Batch quality verified",
        },
        {
            "po_id": "PO-022",
            "component_id": "CMP-005",
            "supplier_id": "SUP-011",
            "quantity": 1500,
            "unit_price": 1.3,
            "total_value": 1950.0,
            "status": "CANCELLED",
            "promised_delivery": (NOW + timedelta(days=25)).isoformat(),
            "current_expected_delivery": None,
            "delay_days": 0,
            "last_erp_sync": NOW.isoformat(),
            "notes": "Cancelled — excess stock identified",
        },
        {
            "po_id": "PO-023",
            "component_id": "CMP-003",
            "supplier_id": "SUP-005",
            "quantity": 800,
            "unit_price": 13.5,
            "total_value": 10800.0,
            "status": "ORDERED",
            "promised_delivery": (NOW + timedelta(days=5)).isoformat(),
            "current_expected_delivery": (NOW + timedelta(days=5)).isoformat(),
            "delay_days": 0,
            "last_erp_sync": NOW.isoformat(),
            "notes": "Emergency order to cover CMP-003 shortage",
        },
        {
            "po_id": "PO-024",
            "component_id": "CMP-004",
            "supplier_id": "SUP-002",
            "quantity": 400,
            "unit_price": 155.0,
            "total_value": 62000.0,
            "status": "OPEN",
            "promised_delivery": (NOW + timedelta(days=7)).isoformat(),
            "current_expected_delivery": (NOW + timedelta(days=7)).isoformat(),
            "delay_days": 0,
            "last_erp_sync": NOW.isoformat(),
            "notes": "Alternative sourcing for VR-5A delay",
        },
        {
            "po_id": "PO-025",
            "component_id": "CMP-006",
            "supplier_id": "SUP-010",
            "quantity": 500,
            "unit_price": 46.0,
            "total_value": 23000.0,
            "status": "IN_TRANSIT",
            "promised_delivery": (NOW + timedelta(days=3)).isoformat(),
            "current_expected_delivery": (NOW + timedelta(days=3)).isoformat(),
            "delay_days": 0,
            "last_erp_sync": NOW.isoformat(),
            "notes": "",
        },
        {
            "po_id": "PO-026",
            "component_id": "CMP-010",
            "supplier_id": "SUP-014",
            "quantity": 1000,
            "unit_price": 2.1,
            "total_value": 2100.0,
            "status": "AT_RISK",
            "promised_delivery": (NOW + timedelta(days=1)).isoformat(),
            "current_expected_delivery": (NOW + timedelta(days=5)).isoformat(),
            "delay_days": 4,
            "last_erp_sync": NOW.isoformat(),
            "notes": "Supplier flagged potential logistics disruption",
        },
    ]
    for po in purchase_orders:
        db["purchase_orders"].update_one({"po_id": po["po_id"]}, {"$set": po}, upsert=True)

    # ------------------------------------------------------------------
    # 4. PRODUCTION ORDERS  (18 — all priority/status variants)
    # ------------------------------------------------------------------
    production_orders = [
        # Critical — blocked by CMP-003 shortage
        {
            "production_id": "WO-001",
            "product": "Industrial Controller IC-7",
            "component_id": "CMP-003",
            "quantity": 300,
            "component_per_unit": 2,
            "components_needed": 600,
            "deadline": (NOW + timedelta(days=3)).isoformat(),
            "priority": "CRITICAL",
            "status": "BLOCKED",
            "notes": "Blocked: MCU stock 60, need 600",
        },
        # Hero scenario — high priority, at risk in 4 days
        {
            "production_id": "WO-002",
            "product": "Widget-X Power Module",
            "component_id": "CMP-004",
            "quantity": 200,
            "component_per_unit": 3,
            "components_needed": 600,
            "deadline": (NOW + timedelta(days=6)).isoformat(),
            "priority": "HIGH",
            "status": "AT_RISK",
            "notes": "Will exhaust current stock in 4 days. PO-001 delayed.",
        },
        # Medium — manageable buffer
        {
            "production_id": "WO-003",
            "product": "Widget-Y Control Board",
            "component_id": "CMP-006",
            "quantity": 50,
            "component_per_unit": 1,
            "components_needed": 50,
            "deadline": (NOW + timedelta(days=12)).isoformat(),
            "priority": "MEDIUM",
            "status": "ON_TRACK",
            "notes": "On track; stock sufficient for 4 days, PO-002 due in 5 days",
        },
        # Low priority — plenty of buffer
        {
            "production_id": "WO-004",
            "product": "Passive Filter Unit",
            "component_id": "CMP-005",
            "quantity": 1000,
            "component_per_unit": 3,
            "components_needed": 3000,
            "deadline": (NOW + timedelta(days=45)).isoformat(),
            "priority": "LOW",
            "status": "ON_TRACK",
            "notes": "Plenty of stock; no action needed",
        },
        # At risk — capacitor supply low
        {
            "production_id": "WO-005",
            "product": "Power Converter PC-10",
            "component_id": "CMP-002",
            "quantity": 100,
            "component_per_unit": 4,
            "components_needed": 400,
            "deadline": (NOW + timedelta(days=2)).isoformat(),
            "priority": "HIGH",
            "status": "AT_RISK",
            "notes": "Capacitor stock at 420, PO-004 at risk — production may pause",
        },
        # Normal — all clear
        {
            "production_id": "WO-006",
            "product": "Signal Amplifier SA-5",
            "component_id": "CMP-001",
            "quantity": 400,
            "component_per_unit": 5,
            "components_needed": 2000,
            "deadline": (NOW + timedelta(days=20)).isoformat(),
            "priority": "MEDIUM",
            "status": "ON_TRACK",
            "notes": "Stock sufficient; PO-003 in transit",
        },
        # Completed recently
        {
            "production_id": "WO-007",
            "product": "PCB Assembly Board V2",
            "component_id": "CMP-007",
            "quantity": 500,
            "component_per_unit": 2,
            "components_needed": 1000,
            "deadline": (NOW - timedelta(days=2)).isoformat(),
            "priority": "HIGH",
            "status": "COMPLETED",
            "notes": "Completed on schedule",
        },
        # Waiting on expedite approval
        {
            "production_id": "WO-008",
            "product": "Servo Driver Module",
            "component_id": "CMP-003",
            "quantity": 150,
            "component_per_unit": 1,
            "components_needed": 150,
            "deadline": (NOW + timedelta(days=5)).isoformat(),
            "priority": "HIGH",
            "status": "WAITING_PARTS",
            "notes": "Waiting on expedite order from SUP-005 for CMP-003",
        },
        # Additional production orders for dashboard richness
        {
            "production_id": "WO-009",
            "product": "RF Transceiver Module",
            "component_id": "CMP-008",
            "quantity": 250,
            "component_per_unit": 2,
            "components_needed": 500,
            "deadline": (NOW + timedelta(days=18)).isoformat(),
            "priority": "MEDIUM",
            "status": "ON_TRACK",
            "notes": "Op-Amp stock healthy, PO-012 on order",
        },
        {
            "production_id": "WO-010",
            "product": "LED Driver Board",
            "component_id": "CMP-009",
            "quantity": 600,
            "component_per_unit": 4,
            "components_needed": 2400,
            "deadline": (NOW + timedelta(days=10)).isoformat(),
            "priority": "MEDIUM",
            "status": "ON_TRACK",
            "notes": "PO-013 in transit, sufficient for 38 days",
        },
        {
            "production_id": "WO-011",
            "product": "Motor Controller MCU Board",
            "component_id": "CMP-010",
            "quantity": 120,
            "component_per_unit": 1,
            "components_needed": 120,
            "deadline": (NOW + timedelta(days=4)).isoformat(),
            "priority": "HIGH",
            "status": "AT_RISK",
            "notes": "PO-014 at risk, may need emergency sourcing",
        },
        {
            "production_id": "WO-012",
            "product": "General Purpose Amplifier",
            "component_id": "CMP-011",
            "quantity": 800,
            "component_per_unit": 3,
            "components_needed": 2400,
            "deadline": (NOW + timedelta(days=30)).isoformat(),
            "priority": "LOW",
            "status": "ON_TRACK",
            "notes": "NPN stock at 12000 — more than adequate",
        },
        {
            "production_id": "WO-013",
            "product": "Voltage Reference Module",
            "component_id": "CMP-012",
            "quantity": 200,
            "component_per_unit": 2,
            "components_needed": 400,
            "deadline": (NOW + timedelta(days=8)).isoformat(),
            "priority": "MEDIUM",
            "status": "ON_TRACK",
            "notes": "Zener stock sufficient; PO-016 delayed but buffer exists",
        },
        {
            "production_id": "WO-014",
            "product": "High-Density SMD Board",
            "component_id": "CMP-013",
            "quantity": 1500,
            "component_per_unit": 10,
            "components_needed": 15000,
            "deadline": (NOW + timedelta(days=25)).isoformat(),
            "priority": "LOW",
            "status": "ON_TRACK",
            "notes": "SMD array at 85000 — vastly over-stocked",
        },
        {
            "production_id": "WO-015",
            "product": "IoT Sensor Hub",
            "component_id": "CMP-014",
            "quantity": 80,
            "component_per_unit": 1,
            "components_needed": 80,
            "deadline": (NOW + timedelta(days=5)).isoformat(),
            "priority": "HIGH",
            "status": "WAITING_PARTS",
            "notes": "DC-DC converter stock at 120; PO-018 due in 9 days — tight",
        },
        {
            "production_id": "WO-016",
            "product": "BLDC Motor Driver",
            "component_id": "CMP-015",
            "quantity": 200,
            "component_per_unit": 1,
            "components_needed": 200,
            "deadline": (NOW + timedelta(days=22)).isoformat(),
            "priority": "MEDIUM",
            "status": "ON_TRACK",
            "notes": "Hall sensor stock healthy; PO-019 ordered",
        },
        {
            "production_id": "WO-017",
            "product": "Temperature Logger v3",
            "component_id": "CMP-016",
            "quantity": 350,
            "component_per_unit": 2,
            "components_needed": 700,
            "deadline": (NOW + timedelta(days=35)).isoformat(),
            "priority": "LOW",
            "status": "COMPLETED",
            "notes": "Early completion; stock surplus allocated to warehouse",
        },
        {
            "production_id": "WO-018",
            "product": "Portable Power Bank Module",
            "component_id": "CMP-017",
            "quantity": 100,
            "component_per_unit": 2,
            "components_needed": 200,
            "deadline": (NOW + timedelta(days=7)).isoformat(),
            "priority": "HIGH",
            "status": "BLOCKED",
            "notes": "Battery stock at 180; PO-020 delayed 11 days — production halted",
        },
    ]
    for p in production_orders:
        db["production_orders"].update_one({"production_id": p["production_id"]}, {"$set": p}, upsert=True)

    # ------------------------------------------------------------------
    # 5. INCIDENTS  (14 — covering all agent state machine paths)
    # ------------------------------------------------------------------
    incidents = [
        # DETECTED — not yet picked up by agent
        {
            "incident_id": "INC-001",
            "type": "SUPPLIER_DELAY",
            "severity": "HIGH",
            "affected_component": "CMP-004",
            "affected_po": "PO-001",
            "supplier_id": "SUP-001",
            "status": "DETECTED",
            "created_at": (NOW - timedelta(hours=2)).isoformat(),
            "source": "erp_event",
            "delay_days": 11,
        },
        # INVESTIGATING — agent triggered, Groq reasoning in progress
        {
            "incident_id": "INC-002",
            "type": "DELIVERY_BREACH",
            "severity": "CRITICAL",
            "affected_component": "CMP-003",
            "affected_po": "PO-007",
            "supplier_id": "SUP-008",
            "status": "INVESTIGATING",
            "created_at": (NOW - timedelta(hours=5)).isoformat(),
            "source": "delivery_monitor",
            "delay_days": 21,
        },
        # WAITING_APPROVAL — requires human approval (>$50k)
        {
            "incident_id": "INC-003",
            "type": "SUPPLIER_DELAY",
            "severity": "HIGH",
            "affected_component": "CMP-003",
            "affected_po": "PO-007",
            "supplier_id": "SUP-008",
            "status": "WAITING_APPROVAL",
            "created_at": (NOW - timedelta(hours=8)).isoformat(),
            "source": "erp_event",
            "delay_days": 21,
            "estimated_recovery_cost": 72000.0,
            "plan_id": "RPL-003",
        },
        # RESOLVED — autonomous recovery executed
        {
            "incident_id": "INC-004",
            "type": "DELIVERY_BREACH",
            "severity": "MEDIUM",
            "affected_component": "CMP-001",
            "affected_po": "PO-009",
            "supplier_id": "SUP-001",
            "status": "RESOLVED",
            "created_at": (NOW - timedelta(days=2)).isoformat(),
            "resolved_at": (NOW - timedelta(hours=12)).isoformat(),
            "source": "delivery_monitor",
            "delay_days": 5,
            "resolution": "Alternative supplier SUP-002 dispatched 300 units. On-time.",
        },
        # REPLANNING — human rejected, agent replanning
        {
            "incident_id": "INC-005",
            "type": "SUPPLIER_DELAY",
            "severity": "MEDIUM",
            "affected_component": "CMP-002",
            "affected_po": "PO-004",
            "supplier_id": "SUP-004",
            "status": "REPLANNING",
            "created_at": (NOW - timedelta(hours=3)).isoformat(),
            "source": "erp_event",
            "delay_days": 3,
            "rejection_reason": "Proposed recovery cost $18,000 approved limit $15,000 — need cheaper option",
        },
        # DATA_INCONSISTENCY — flagged by LLM during analysis
        {
            "incident_id": "INC-006",
            "type": "DATA_INCONSISTENCY",
            "severity": "LOW",
            "affected_component": "CMP-999",
            "affected_po": "PO-000",
            "supplier_id": "SUP-UNKNOWN",
            "status": "DETECTED",
            "created_at": (NOW - timedelta(minutes=30)).isoformat(),
            "source": "groq_agent",
            "notes": "LLM detected: supplier SUP-UNKNOWN not registered, PO has no delivery date",
        },
        # Additional incidents for dashboard richness
        {
            "incident_id": "INC-007",
            "type": "DELIVERY_BREACH",
            "severity": "HIGH",
            "affected_component": "CMP-017",
            "affected_po": "PO-020",
            "supplier_id": "SUP-009",
            "status": "INVESTIGATING",
            "created_at": (NOW - timedelta(hours=4)).isoformat(),
            "source": "delivery_monitor",
            "delay_days": 11,
        },
        {
            "incident_id": "INC-008",
            "type": "SUPPLIER_DELAY",
            "severity": "MEDIUM",
            "affected_component": "CMP-012",
            "affected_po": "PO-016",
            "supplier_id": "SUP-013",
            "status": "DETECTED",
            "created_at": (NOW - timedelta(hours=1)).isoformat(),
            "source": "erp_event",
            "delay_days": 6,
        },
        {
            "incident_id": "INC-009",
            "type": "DELIVERY_BREACH",
            "severity": "MEDIUM",
            "affected_component": "CMP-010",
            "affected_po": "PO-014",
            "supplier_id": "SUP-011",
            "status": "DETECTED",
            "created_at": (NOW - timedelta(minutes=45)).isoformat(),
            "source": "delivery_monitor",
            "delay_days": 4,
        },
        {
            "incident_id": "INC-010",
            "type": "SUPPLIER_DELAY",
            "severity": "LOW",
            "affected_component": "CMP-010",
            "affected_po": "PO-026",
            "supplier_id": "SUP-014",
            "status": "RESOLVED",
            "created_at": (NOW - timedelta(days=3)).isoformat(),
            "resolved_at": (NOW - timedelta(days=1)).isoformat(),
            "source": "erp_event",
            "delay_days": 4,
            "resolution": "Supplier expedited shipment — 1-day delay only.",
        },
        {
            "incident_id": "INC-011",
            "type": "DELIVERY_BREACH",
            "severity": "CRITICAL",
            "affected_component": "CMP-004",
            "affected_po": "PO-001",
            "supplier_id": "SUP-001",
            "status": "WAITING_APPROVAL",
            "created_at": (NOW - timedelta(hours=6)).isoformat(),
            "source": "delivery_monitor",
            "delay_days": 11,
            "estimated_recovery_cost": 93000.0,
            "plan_id": "RPL-004",
        },
        {
            "incident_id": "INC-012",
            "type": "SUPPLIER_DELAY",
            "severity": "HIGH",
            "affected_component": "CMP-003",
            "affected_po": "PO-023",
            "supplier_id": "SUP-005",
            "status": "EXECUTING",
            "created_at": (NOW - timedelta(hours=10)).isoformat(),
            "source": "erp_event",
            "delay_days": 3,
        },
        {
            "incident_id": "INC-013",
            "type": "DELIVERY_BREACH",
            "severity": "MEDIUM",
            "affected_component": "CMP-002",
            "affected_po": "PO-004",
            "supplier_id": "SUP-004",
            "status": "RESOLVED",
            "created_at": (NOW - timedelta(days=5)).isoformat(),
            "resolved_at": (NOW - timedelta(days=4)).isoformat(),
            "source": "delivery_monitor",
            "delay_days": 3,
            "resolution": "Partial shipment received; remainder confirmed for next week.",
        },
        {
            "incident_id": "INC-014",
            "type": "SUPPLIER_DELAY",
            "severity": "LOW",
            "affected_component": "CMP-008",
            "affected_po": "PO-012",
            "supplier_id": "SUP-009",
            "status": "DETECTED",
            "created_at": (NOW - timedelta(minutes=15)).isoformat(),
            "source": "erp_event",
            "delay_days": 2,
        },
    ]
    for inc in incidents:
        db["incidents"].update_one({"incident_id": inc["incident_id"]}, {"$set": inc}, upsert=True)

    # ------------------------------------------------------------------
    # 6. RFQ RESPONSES  (10 — accepted, rejected, expedite, missing, partial)
    # ------------------------------------------------------------------
    rfq_responses = [
        {
            "rfq_id": "RFQ-001",
            "supplier_id": "SUP-002",
            "component_id": "CMP-004",
            "quantity": 600,
            "unit_price": 155.0,
            "delivery_days": 7,
            "total_cost": 93000.0,
            "expedite_available": False,
            "expedite_fee": None,
            "accepted": True,
            "received_at": (NOW - timedelta(hours=1)).isoformat(),
        },
        {
            "rfq_id": "RFQ-002",
            "supplier_id": "SUP-003",
            "component_id": "CMP-004",
            "quantity": 600,
            "unit_price": 165.0,
            "delivery_days": 3,
            "total_cost": 99000.0,
            "expedite_available": True,
            "expedite_fee": 4500.0,
            "accepted": None,  # pending decision
            "received_at": (NOW - timedelta(minutes=45)).isoformat(),
        },
        {
            "rfq_id": "RFQ-003",
            "supplier_id": "SUP-004",
            "component_id": "CMP-004",
            "quantity": 600,
            "unit_price": 125.0,
            "delivery_days": 21,
            "total_cost": 75000.0,
            "expedite_available": False,
            "expedite_fee": None,
            "accepted": False,  # rejected — lead time too long
            "rejection_reason": "21 days exceeds required delivery window of 8 days",
            "received_at": (NOW - timedelta(hours=2)).isoformat(),
        },
        {
            "rfq_id": "RFQ-004",
            "supplier_id": "SUP-005",
            "component_id": "CMP-003",
            "quantity": 5000,
            "unit_price": 13.5,
            "delivery_days": 5,
            "total_cost": 67500.0,
            "expedite_available": True,
            "expedite_fee": 2000.0,
            "accepted": None,
            "received_at": (NOW - timedelta(hours=3)).isoformat(),
        },
        {
            "rfq_id": "RFQ-005",
            "supplier_id": "SUP-007",
            "component_id": "CMP-006",
            "quantity": None,
            "unit_price": None,
            "delivery_days": None,
            "total_cost": None,
            "expedite_available": False,
            "expedite_fee": None,
            "accepted": None,
            "notes": "Supplier acknowledged RFQ but could not provide quote",
            "received_at": NOW.isoformat(),
        },
        # Additional RFQs
        {
            "rfq_id": "RFQ-006",
            "supplier_id": "SUP-009",
            "component_id": "CMP-017",
            "quantity": 500,
            "unit_price": 9.2,
            "delivery_days": 10,
            "total_cost": 4600.0,
            "expedite_available": True,
            "expedite_fee": 500.0,
            "accepted": None,
            "received_at": (NOW - timedelta(hours=2)).isoformat(),
        },
        {
            "rfq_id": "RFQ-007",
            "supplier_id": "SUP-011",
            "component_id": "CMP-010",
            "quantity": 1000,
            "unit_price": 2.15,
            "delivery_days": 8,
            "total_cost": 2150.0,
            "expedite_available": False,
            "expedite_fee": None,
            "accepted": True,
            "received_at": (NOW - timedelta(hours=5)).isoformat(),
        },
        {
            "rfq_id": "RFQ-008",
            "supplier_id": "SUP-012",
            "component_id": "CMP-012",
            "quantity": 3000,
            "unit_price": 0.40,
            "delivery_days": 14,
            "total_cost": 1200.0,
            "expedite_available": True,
            "expedite_fee": 200.0,
            "accepted": True,
            "received_at": (NOW - timedelta(hours=6)).isoformat(),
        },
        {
            "rfq_id": "RFQ-009",
            "supplier_id": "SUP-013",
            "component_id": "CMP-014",
            "quantity": 300,
            "unit_price": 19.0,
            "delivery_days": 15,
            "total_cost": 5700.0,
            "expedite_available": False,
            "expedite_fee": None,
            "accepted": False,
            "rejection_reason": "Lead time 15 days exceeds required 9 days",
            "received_at": (NOW - timedelta(hours=1, minutes=30)).isoformat(),
        },
        {
            "rfq_id": "RFQ-010",
            "supplier_id": "SUP-014",
            "component_id": "CMP-014",
            "quantity": 300,
            "unit_price": 18.5,
            "delivery_days": 9,
            "total_cost": 5550.0,
            "expedite_available": True,
            "expedite_fee": 300.0,
            "accepted": None,
            "received_at": (NOW - timedelta(minutes=20)).isoformat(),
        },
    ]
    for rfq in rfq_responses:
        db["rfq_responses"].update_one(
            {"rfq_id": rfq["rfq_id"], "supplier_id": rfq["supplier_id"]},
            {"$set": rfq},
            upsert=True,
        )

    # ------------------------------------------------------------------
    # 7. RECOVERY PLANS  (5 — autonomous, approval-required, rejected)
    # ------------------------------------------------------------------
    recovery_plans = [
        {
            "plan_id": "RPL-001",
            "incident_id": "INC-001",
            "component_id": "CMP-004",
            "created_at": (NOW - timedelta(hours=1)).isoformat(),
            "requires_human_approval": False,
            "approval_threshold_usd": 50000.0,
            "recommended_option_id": "A",
            "recommendation_reason": "Option A uses SUP-002 with 91% reliability and 7-day delivery within budget.",
            "options": [
                {
                    "option_id": "A",
                    "allocations": [{"supplier_id": "SUP-002", "quantity": 600, "unit_price": 155.0, "delivery_days": 7}],
                    "total_cost": 93000.0,
                    "max_delivery_days": 7,
                    "constraints_satisfied": True,
                    "rejection_reason": None,
                },
                {
                    "option_id": "B",
                    "allocations": [
                        {"supplier_id": "SUP-003", "quantity": 300, "unit_price": 165.0, "delivery_days": 3},
                        {"supplier_id": "SUP-002", "quantity": 300, "unit_price": 155.0, "delivery_days": 7},
                    ],
                    "total_cost": 96000.0,
                    "max_delivery_days": 7,
                    "constraints_satisfied": True,
                    "rejection_reason": None,
                },
            ],
        },
        {
            "plan_id": "RPL-002",
            "incident_id": "INC-004",
            "component_id": "CMP-001",
            "created_at": (NOW - timedelta(days=2, hours=1)).isoformat(),
            "requires_human_approval": False,
            "approval_threshold_usd": 50000.0,
            "recommended_option_id": "A",
            "recommendation_reason": "Low cost, fast alternative from SUP-002. Autonomous approval granted.",
            "status": "EXECUTED",
            "executed_at": (NOW - timedelta(hours=12)).isoformat(),
            "options": [
                {
                    "option_id": "A",
                    "allocations": [{"supplier_id": "SUP-002", "quantity": 300, "unit_price": 2.7, "delivery_days": 5}],
                    "total_cost": 810.0,
                    "max_delivery_days": 5,
                    "constraints_satisfied": True,
                    "rejection_reason": None,
                },
            ],
        },
        {
            "plan_id": "RPL-003",
            "incident_id": "INC-003",
            "component_id": "CMP-003",
            "created_at": (NOW - timedelta(hours=6)).isoformat(),
            "requires_human_approval": True,
            "approval_threshold_usd": 50000.0,
            "estimated_cost": 72000.0,
            "recommended_option_id": "A",
            "recommendation_reason": "Only option that meets quality and delivery requirements. Exceeds $50k threshold.",
            "status": "AWAITING_APPROVAL",
            "options": [
                {
                    "option_id": "A",
                    "allocations": [{"supplier_id": "SUP-005", "quantity": 5000, "unit_price": 13.5, "delivery_days": 5}],
                    "total_cost": 72000.0,
                    "max_delivery_days": 5,
                    "constraints_satisfied": True,
                    "rejection_reason": None,
                },
                {
                    "option_id": "B",
                    "allocations": [{"supplier_id": "SUP-004", "quantity": 5000, "unit_price": 10.0, "delivery_days": 30}],
                    "total_cost": 50000.0,
                    "max_delivery_days": 30,
                    "constraints_satisfied": False,
                    "rejection_reason": "Delivery window 30 days exceeds required 5 days",
                },
            ],
        },
        {
            "plan_id": "RPL-004",
            "incident_id": "INC-011",
            "component_id": "CMP-004",
            "created_at": (NOW - timedelta(hours=5)).isoformat(),
            "requires_human_approval": True,
            "approval_threshold_usd": 50000.0,
            "estimated_cost": 93000.0,
            "recommended_option_id": "A",
            "recommendation_reason": "SUP-002 is the highest-reliability option within acceptable lead time.",
            "status": "AWAITING_APPROVAL",
            "options": [
                {
                    "option_id": "A",
                    "allocations": [{"supplier_id": "SUP-002", "quantity": 600, "unit_price": 155.0, "delivery_days": 7}],
                    "total_cost": 93000.0,
                    "max_delivery_days": 7,
                    "constraints_satisfied": True,
                    "rejection_reason": None,
                },
            ],
        },
        {
            "plan_id": "RPL-005",
            "incident_id": "INC-007",
            "component_id": "CMP-017",
            "created_at": (NOW - timedelta(hours=3)).isoformat(),
            "requires_human_approval": False,
            "approval_threshold_usd": 50000.0,
            "recommended_option_id": "A",
            "recommendation_reason": "SUP-009 expedite available at acceptable cost. Autonomous approval.",
            "status": "AWAITING_APPROVAL",
            "options": [
                {
                    "option_id": "A",
                    "allocations": [{"supplier_id": "SUP-009", "quantity": 500, "unit_price": 9.2, "delivery_days": 10}],
                    "total_cost": 4600.0,
                    "max_delivery_days": 10,
                    "constraints_satisfied": True,
                    "rejection_reason": None,
                },
            ],
        },
    ]
    for plan in recovery_plans:
        db["recovery_plans"].update_one({"plan_id": plan["plan_id"]}, {"$set": plan}, upsert=True)

    # ------------------------------------------------------------------
    # 8. SEED AUDIT LOGS  (17 entries — pre-populated for dashboard demo)
    # ------------------------------------------------------------------
    audit_logs = [
        {
            "event_id": "AUD-001",
            "timestamp": (NOW - timedelta(hours=8)).isoformat(),
            "source": "n8n",
            "workflow": "ERP_EVENT_SYNC",
            "event_type": "ERP_SYNC_COMPLETED",
            "incident_id": "INC-003",
            "entity_type": "PURCHASE_ORDER",
            "entity_id": "PO-007",
            "action": "SYNC_ERP_EVENT",
            "status": "SUCCESS",
            "tool": "SYNC_ERP_EVENT",
            "result": "SUCCESS",
            "decision": "ERP_SYNC_COMPLETED",
            "reason": "n8n workflow: ERP_EVENT_SYNC",
            "retry_count": 0,
            "correlation_id": "CORR-001",
            "input": {"event_type": "STATUS_UPDATE", "status": "DELAYED"},
            "output": {"incident_id": "INC-003", "agent_trigger_required": True},
            "ingested_at": (NOW - timedelta(hours=8)).isoformat(),
        },
        {
            "event_id": "AUD-002",
            "timestamp": (NOW - timedelta(hours=7, minutes=55)).isoformat(),
            "source": "n8n",
            "workflow": "GROQ_AI_AGENT",
            "event_type": "AUTONOMOUS_APPROVAL",
            "incident_id": "INC-004",
            "entity_type": "INCIDENT",
            "entity_id": "INC-004",
            "action": "GROQ_REASONING_COMPLETE",
            "status": "SUCCESS",
            "tool": "GROQ_REASONING_COMPLETE",
            "result": "SUCCESS",
            "decision": "APPROVE_AUTONOMOUS",
            "reason": "Stock sufficient; cost $810 well below $50k threshold",
            "retry_count": 0,
            "correlation_id": "CORR-002",
            "input": {"incident_id": "INC-004"},
            "output": {"decision": "APPROVE_AUTONOMOUS", "recommended_action": "Place order with SUP-002"},
            "ingested_at": (NOW - timedelta(hours=7, minutes=55)).isoformat(),
        },
        {
            "event_id": "AUD-003",
            "timestamp": (NOW - timedelta(hours=7)).isoformat(),
            "source": "n8n",
            "workflow": "GROQ_AI_AGENT",
            "event_type": "HUMAN_APPROVAL_REQUIRED",
            "incident_id": "INC-003",
            "entity_type": "INCIDENT",
            "entity_id": "INC-003",
            "action": "GROQ_REASONING_COMPLETE",
            "status": "SUCCESS",
            "tool": "GROQ_REASONING_COMPLETE",
            "result": "ESCALATED",
            "decision": "NEEDS_HUMAN_APPROVAL",
            "reason": "Estimated recovery cost ₹72,000 exceeds ₹50,000 autonomous limit",
            "retry_count": 0,
            "correlation_id": "CORR-003",
            "input": {"incident_id": "INC-003"},
            "output": {"decision": "NEEDS_HUMAN_APPROVAL", "estimated_cost": 72000.0},
            "ingested_at": (NOW - timedelta(hours=7)).isoformat(),
        },
        {
            "event_id": "AUD-004",
            "timestamp": (NOW - timedelta(hours=6, minutes=30)).isoformat(),
            "source": "n8n",
            "workflow": "HUMAN_APPROVAL_ORCHESTRATOR",
            "event_type": "APPROVAL_REQUEST_SENT",
            "incident_id": "INC-003",
            "entity_type": "RECOVERY_PLAN",
            "entity_id": "RPL-003",
            "action": "SEND_APPROVAL_EMAIL",
            "status": "SUCCESS",
            "tool": "SEND_APPROVAL_EMAIL",
            "result": "SUCCESS",
            "decision": "APPROVAL_REQUEST_SENT",
            "reason": "Email dispatched to procurement@atlas-scm.io",
            "retry_count": 0,
            "correlation_id": "CORR-004",
            "input": {"estimated_cost": 72000.0, "risk": "HIGH"},
            "output": {"channel": "email"},
            "ingested_at": (NOW - timedelta(hours=6, minutes=30)).isoformat(),
        },
        {
            "event_id": "AUD-005",
            "timestamp": (NOW - timedelta(hours=3)).isoformat(),
            "source": "n8n",
            "workflow": "SUPPLIER_RESPONSE_SYNC",
            "event_type": "SUPPLIER_RESPONSE_RECEIVED",
            "incident_id": "INC-001",
            "entity_type": "RFQ",
            "entity_id": "RFQ-001",
            "action": "SYNC_SUPPLIER_RESPONSE",
            "status": "SUCCESS",
            "tool": "SYNC_SUPPLIER_RESPONSE",
            "result": "SUCCESS",
            "decision": "SUPPLIER_RESPONSE_RECEIVED",
            "reason": "n8n workflow: SUPPLIER_RESPONSE_SYNC",
            "retry_count": 0,
            "correlation_id": "CORR-005",
            "input": {"supplier_id": "SUP-002", "component_id": "CMP-004", "delivery_days": 7},
            "output": {"rfq_id": "RFQ-001", "accepted": True},
            "ingested_at": (NOW - timedelta(hours=3)).isoformat(),
        },
        {
            "event_id": "AUD-006",
            "timestamp": (NOW - timedelta(hours=1)).isoformat(),
            "source": "n8n",
            "workflow": "DELIVERY_COMMITMENT_MONITOR",
            "event_type": "DELIVERY_COMMITMENT_BREACH",
            "incident_id": "INC-002",
            "entity_type": "PURCHASE_ORDER",
            "entity_id": "PO-007",
            "action": "TRIGGER_GROQ_AGENT",
            "status": "SUCCESS",
            "tool": "TRIGGER_GROQ_AGENT",
            "result": "SUCCESS",
            "decision": "DELIVERY_COMMITMENT_BREACH",
            "reason": "n8n workflow: DELIVERY_COMMITMENT_MONITOR",
            "retry_count": 0,
            "correlation_id": "CORR-006",
            "input": {"promised_date": (NOW - timedelta(days=7)).isoformat(), "delay_days": 21},
            "output": {"agent_triggered": True, "incident_id": "INC-002"},
            "ingested_at": (NOW - timedelta(hours=1)).isoformat(),
        },
        {
            "event_id": "AUD-007",
            "timestamp": (NOW - timedelta(minutes=30)).isoformat(),
            "source": "n8n",
            "workflow": "GROQ_AI_AGENT",
            "event_type": "DATA_INCONSISTENCY_DETECTED",
            "incident_id": "INC-006",
            "entity_type": "PURCHASE_ORDER",
            "entity_id": "PO-000",
            "action": "GROQ_INCONSISTENCY_DETECTION",
            "status": "SUCCESS",
            "tool": "GROQ_INCONSISTENCY_DETECTION",
            "result": "ESCALATED",
            "decision": "DATA_INCONSISTENCY",
            "reason": "Supplier SUP-UNKNOWN not in system; missing delivery dates; zero unit price",
            "retry_count": 0,
            "correlation_id": "CORR-007",
            "input": {"incident_id": "INC-006"},
            "output": {"inconsistencies": ["unknown_supplier", "missing_delivery_date", "zero_unit_price"]},
            "ingested_at": (NOW - timedelta(minutes=30)).isoformat(),
        },
        # Additional audit logs for dashboard richness
        {
            "event_id": "AUD-008",
            "timestamp": (NOW - timedelta(hours=4)).isoformat(),
            "source": "n8n",
            "workflow": "ERP_EVENT_SYNC",
            "event_type": "ERP_SYNC_COMPLETED",
            "incident_id": "INC-007",
            "entity_type": "PURCHASE_ORDER",
            "entity_id": "PO-020",
            "action": "SYNC_ERP_EVENT",
            "status": "SUCCESS",
            "tool": "SYNC_ERP_EVENT",
            "result": "SUCCESS",
            "decision": "ERP_SYNC_COMPLETED",
            "reason": "Battery supply delay detected via ERP sync",
            "retry_count": 0,
            "correlation_id": "CORR-008",
            "input": {"event_type": "STATUS_UPDATE", "status": "DELAYED"},
            "output": {"incident_id": "INC-007", "agent_trigger_required": True},
            "ingested_at": (NOW - timedelta(hours=4)).isoformat(),
        },
        {
            "event_id": "AUD-009",
            "timestamp": (NOW - timedelta(hours=4, minutes=30)).isoformat(),
            "source": "n8n",
            "workflow": "GROQ_AI_AGENT",
            "event_type": "INVESTIGATING",
            "incident_id": "INC-007",
            "entity_type": "INCIDENT",
            "entity_id": "INC-007",
            "action": "GROQ_CONTEXT_FETCH",
            "status": "SUCCESS",
            "tool": "GET_SUPPLIER_INFO",
            "result": "SUCCESS",
            "decision": "INVESTIGATING",
            "reason": "Fetching supplier SUP-009 profile and inventory for CMP-017",
            "retry_count": 0,
            "correlation_id": "CORR-009",
            "input": {"incident_id": "INC-007"},
            "output": {"supplier": "SUP-009", "component": "CMP-017", "delay_days": 11},
            "ingested_at": (NOW - timedelta(hours=4, minutes=30)).isoformat(),
        },
        {
            "event_id": "AUD-010",
            "timestamp": (NOW - timedelta(hours=10)).isoformat(),
            "source": "n8n",
            "workflow": "GROQ_AI_AGENT",
            "event_type": "EXECUTING",
            "incident_id": "INC-012",
            "entity_type": "INCIDENT",
            "entity_id": "INC-012",
            "action": "EXECUTE_RECOVERY_PLAN",
            "status": "SUCCESS",
            "tool": "PLACE_PURCHASE_ORDER",
            "result": "SUCCESS",
            "decision": "APPROVE_AUTONOMOUS",
            "reason": "Emergency order placed with SUP-005 for CMP-003 (800 units)",
            "retry_count": 0,
            "correlation_id": "CORR-010",
            "input": {"incident_id": "INC-012"},
            "output": {"po_id": "PO-023", "status": "ORDERED"},
            "ingested_at": (NOW - timedelta(hours=10)).isoformat(),
        },
        {
            "event_id": "AUD-011",
            "timestamp": (NOW - timedelta(days=3, hours=2)).isoformat(),
            "source": "n8n",
            "workflow": "DELIVERY_COMMITMENT_MONITOR",
            "event_type": "DELIVERY_COMMITMENT_BREACH",
            "incident_id": "INC-013",
            "entity_type": "PURCHASE_ORDER",
            "entity_id": "PO-004",
            "action": "TRIGGER_GROQ_AGENT",
            "status": "SUCCESS",
            "tool": "TRIGGER_GROQ_AGENT",
            "result": "SUCCESS",
            "decision": "DELIVERY_COMMITMENT_BREACH",
            "reason": "CMP-002 capacitor partial delivery breach detected",
            "retry_count": 0,
            "correlation_id": "CORR-011",
            "input": {"promised_date": (NOW - timedelta(days=5)).isoformat(), "delay_days": 3},
            "output": {"agent_triggered": True, "incident_id": "INC-013"},
            "ingested_at": (NOW - timedelta(days=3, hours=2)).isoformat(),
        },
        {
            "event_id": "AUD-012",
            "timestamp": (NOW - timedelta(days=4, hours=5)).isoformat(),
            "source": "n8n",
            "workflow": "GROQ_AI_AGENT",
            "event_type": "RESOLVED",
            "incident_id": "INC-010",
            "entity_type": "INCIDENT",
            "entity_id": "INC-010",
            "action": "GROQ_REASONING_COMPLETE",
            "status": "SUCCESS",
            "tool": "GROQ_REASONING_COMPLETE",
            "result": "SUCCESS",
            "decision": "APPROVE_AUTONOMOUS",
            "reason": "Supplier expedited; minor delay resolved autonomously",
            "retry_count": 0,
            "correlation_id": "CORR-012",
            "input": {"incident_id": "INC-010"},
            "output": {"decision": "APPROVE_AUTONOMOUS", "delay_resolved": True},
            "ingested_at": (NOW - timedelta(days=4, hours=5)).isoformat(),
        },
        {
            "event_id": "AUD-013",
            "timestamp": (NOW - timedelta(hours=6)).isoformat(),
            "source": "n8n",
            "workflow": "GROQ_AI_AGENT",
            "event_type": "HUMAN_APPROVAL_REQUIRED",
            "incident_id": "INC-011",
            "entity_type": "INCIDENT",
            "entity_id": "INC-011",
            "action": "GROQ_REASONING_COMPLETE",
            "status": "SUCCESS",
            "tool": "GROQ_REASONING_COMPLETE",
            "result": "ESCALATED",
            "decision": "NEEDS_HUMAN_APPROVAL",
            "reason": "Recovery cost ₹93,000 exceeds ₹50,000 autonomous approval limit",
            "retry_count": 0,
            "correlation_id": "CORR-013",
            "input": {"incident_id": "INC-011"},
            "output": {"decision": "NEEDS_HUMAN_APPROVAL", "estimated_cost": 93000.0},
            "ingested_at": (NOW - timedelta(hours=6)).isoformat(),
        },
        {
            "event_id": "AUD-014",
            "timestamp": (NOW - timedelta(hours=1, minutes=30)).isoformat(),
            "source": "n8n",
            "workflow": "ERP_EVENT_SYNC",
            "event_type": "ERP_SYNC_COMPLETED",
            "incident_id": "INC-008",
            "entity_type": "PURCHASE_ORDER",
            "entity_id": "PO-016",
            "action": "SYNC_ERP_EVENT",
            "status": "SUCCESS",
            "tool": "SYNC_ERP_EVENT",
            "result": "SUCCESS",
            "decision": "ERP_SYNC_COMPLETED",
            "reason": "Customs delay at Zener shipment origin port",
            "retry_count": 0,
            "correlation_id": "CORR-014",
            "input": {"event_type": "STATUS_UPDATE", "status": "DELAYED"},
            "output": {"incident_id": "INC-008", "agent_trigger_required": True},
            "ingested_at": (NOW - timedelta(hours=1, minutes=30)).isoformat(),
        },
        {
            "event_id": "AUD-015",
            "timestamp": (NOW - timedelta(minutes=45)).isoformat(),
            "source": "n8n",
            "workflow": "DELIVERY_COMMITMENT_MONITOR",
            "event_type": "DELIVERY_COMMITMENT_BREACH",
            "incident_id": "INC-009",
            "entity_type": "PURCHASE_ORDER",
            "entity_id": "PO-014",
            "action": "TRIGGER_GROQ_AGENT",
            "status": "SUCCESS",
            "tool": "TRIGGER_GROQ_AGENT",
            "result": "SUCCESS",
            "decision": "DELIVERY_COMMITMENT_BREACH",
            "reason": "Crystal oscillator PO breach: 4-day delay projected",
            "retry_count": 0,
            "correlation_id": "CORR-015",
            "input": {"promised_date": (NOW + timedelta(days=2)).isoformat(), "delay_days": 4},
            "output": {"agent_triggered": True, "incident_id": "INC-009"},
            "ingested_at": (NOW - timedelta(minutes=45)).isoformat(),
        },
        {
            "event_id": "AUD-016",
            "timestamp": (NOW - timedelta(minutes=15)).isoformat(),
            "source": "n8n",
            "workflow": "ERP_EVENT_SYNC",
            "event_type": "ERP_SYNC_COMPLETED",
            "incident_id": "INC-014",
            "entity_type": "PURCHASE_ORDER",
            "entity_id": "PO-012",
            "action": "SYNC_ERP_EVENT",
            "status": "SUCCESS",
            "tool": "SYNC_ERP_EVENT",
            "result": "SUCCESS",
            "decision": "ERP_SYNC_COMPLETED",
            "reason": "Minor 2-day delay on Op-Amp order from SUP-009",
            "retry_count": 0,
            "correlation_id": "CORR-016",
            "input": {"event_type": "STATUS_UPDATE", "status": "DELAYED"},
            "output": {"incident_id": "INC-014", "agent_trigger_required": False},
            "ingested_at": (NOW - timedelta(minutes=15)).isoformat(),
        },
        {
            "event_id": "AUD-017",
            "timestamp": (NOW - timedelta(hours=5, minutes=15)).isoformat(),
            "source": "n8n",
            "workflow": "SUPPLIER_RESPONSE_SYNC",
            "event_type": "SUPPLIER_RESPONSE_RECEIVED",
            "incident_id": "INC-009",
            "entity_type": "RFQ",
            "entity_id": "RFQ-007",
            "action": "SYNC_SUPPLIER_RESPONSE",
            "status": "SUCCESS",
            "tool": "SYNC_SUPPLIER_RESPONSE",
            "result": "SUCCESS",
            "decision": "SUPPLIER_RESPONSE_RECEIVED",
            "reason": "SUP-011 quote accepted for CMP-010 replacement",
            "retry_count": 0,
            "correlation_id": "CORR-017",
            "input": {"supplier_id": "SUP-011", "component_id": "CMP-010", "delivery_days": 8},
            "output": {"rfq_id": "RFQ-007", "accepted": True},
            "ingested_at": (NOW - timedelta(hours=5, minutes=15)).isoformat(),
        },
    ]
    for log in audit_logs:
        db["audit_logs"].update_one({"event_id": log["event_id"]}, {"$set": log}, upsert=True)

    # ------------------------------------------------------------------
    # 9. ERP LOGS  (tracking all ERP updates made by the agent)
    # ------------------------------------------------------------------
    erp_logs = [
        {
            "log_id": "ERP-001",
            "timestamp": (NOW - timedelta(hours=12)).isoformat(),
            "action": "PO_CREATED",
            "entity_type": "PURCHASE_ORDER",
            "entity_id": "PO-003",
            "incident_id": "INC-004",
            "performed_by": "n8n:GROQ_AI_AGENT",
            "details": {"supplier_id": "SUP-002", "quantity": 300, "unit_price": 2.7},
            "status": "SUCCESS",
            "correlation_id": "CORR-002",
        },
        {
            "log_id": "ERP-002",
            "timestamp": (NOW - timedelta(hours=11)).isoformat(),
            "action": "INCIDENT_STATUS_UPDATE",
            "entity_type": "INCIDENT",
            "entity_id": "INC-004",
            "incident_id": "INC-004",
            "performed_by": "n8n:GROQ_AI_AGENT",
            "details": {"old_status": "INVESTIGATING", "new_status": "RESOLVED"},
            "status": "SUCCESS",
            "correlation_id": "CORR-002",
        },
        {
            "log_id": "ERP-003",
            "timestamp": (NOW - timedelta(hours=10)).isoformat(),
            "action": "PO_CREATED",
            "entity_type": "PURCHASE_ORDER",
            "entity_id": "PO-023",
            "incident_id": "INC-012",
            "performed_by": "n8n:GROQ_AI_AGENT",
            "details": {"supplier_id": "SUP-005", "quantity": 800, "unit_price": 13.5},
            "status": "SUCCESS",
            "correlation_id": "CORR-010",
        },
        {
            "log_id": "ERP-004",
            "timestamp": (NOW - timedelta(days=1)).isoformat(),
            "action": "INCIDENT_STATUS_UPDATE",
            "entity_type": "INCIDENT",
            "entity_id": "INC-010",
            "incident_id": "INC-010",
            "performed_by": "n8n:GROQ_AI_AGENT",
            "details": {"old_status": "INVESTIGATING", "new_status": "RESOLVED"},
            "status": "SUCCESS",
            "correlation_id": "CORR-012",
        },
        {
            "log_id": "ERP-005",
            "timestamp": (NOW - timedelta(days=4)).isoformat(),
            "action": "INCIDENT_STATUS_UPDATE",
            "entity_type": "INCIDENT",
            "entity_id": "INC-013",
            "incident_id": "INC-013",
            "performed_by": "n8n:GROQ_AI_AGENT",
            "details": {"old_status": "INVESTIGATING", "new_status": "RESOLVED"},
            "status": "SUCCESS",
            "correlation_id": "CORR-011",
        },
    ]
    for log in erp_logs:
        db["erp_logs"].update_one({"log_id": log["log_id"]}, {"$set": log}, upsert=True)

    print("SUCCESS: Database seeded with comprehensive data.")
    print(f"   Inventory:         {len(inventory_data)} items")
    print(f"   Suppliers:         {len(suppliers)} suppliers")
    print(f"   Purchase Orders:   {len(purchase_orders)} orders")
    print(f"   Production Orders: {len(production_orders)} orders")
    print(f"   Incidents:         {len(incidents)} incidents")
    print(f"   RFQ Responses:     {len(rfq_responses)} responses")
    print(f"   Recovery Plans:    {len(recovery_plans)} plans")
    print(f"   Audit Logs:        {len(audit_logs)} entries (pre-seeded)")
    print(f"   ERP Logs:          {len(erp_logs)} entries (pre-seeded)")